// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoZMQ.proto

package com.randomm.server;

public final class ProtoBufMessage {
  private ProtoBufMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FingerPrintOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string fingerPrint = 1;
    /**
     * <code>required string fingerPrint = 1;</code>
     */
    boolean hasFingerPrint();
    /**
     * <code>required string fingerPrint = 1;</code>
     */
    java.lang.String getFingerPrint();
    /**
     * <code>required string fingerPrint = 1;</code>
     */
    com.google.protobuf.ByteString
        getFingerPrintBytes();
  }
  /**
   * Protobuf type {@code akka.FingerPrint}
   */
  public static final class FingerPrint extends
      com.google.protobuf.GeneratedMessage
      implements FingerPrintOrBuilder {
    // Use FingerPrint.newBuilder() to construct.
    private FingerPrint(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FingerPrint(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FingerPrint defaultInstance;
    public static FingerPrint getDefaultInstance() {
      return defaultInstance;
    }

    public FingerPrint getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FingerPrint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fingerPrint_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randomm.server.ProtoBufMessage.internal_static_akka_FingerPrint_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randomm.server.ProtoBufMessage.internal_static_akka_FingerPrint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.randomm.server.ProtoBufMessage.FingerPrint.class, com.randomm.server.ProtoBufMessage.FingerPrint.Builder.class);
    }

    public static com.google.protobuf.Parser<FingerPrint> PARSER =
        new com.google.protobuf.AbstractParser<FingerPrint>() {
      public FingerPrint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FingerPrint(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FingerPrint> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string fingerPrint = 1;
    public static final int FINGERPRINT_FIELD_NUMBER = 1;
    private java.lang.Object fingerPrint_;
    /**
     * <code>required string fingerPrint = 1;</code>
     */
    public boolean hasFingerPrint() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string fingerPrint = 1;</code>
     */
    public java.lang.String getFingerPrint() {
      java.lang.Object ref = fingerPrint_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fingerPrint_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fingerPrint = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFingerPrintBytes() {
      java.lang.Object ref = fingerPrint_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fingerPrint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      fingerPrint_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFingerPrint()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFingerPrintBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFingerPrintBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.randomm.server.ProtoBufMessage.FingerPrint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.randomm.server.ProtoBufMessage.FingerPrint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.randomm.server.ProtoBufMessage.FingerPrint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.randomm.server.ProtoBufMessage.FingerPrint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.randomm.server.ProtoBufMessage.FingerPrint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.randomm.server.ProtoBufMessage.FingerPrint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.randomm.server.ProtoBufMessage.FingerPrint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.randomm.server.ProtoBufMessage.FingerPrint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.randomm.server.ProtoBufMessage.FingerPrint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.randomm.server.ProtoBufMessage.FingerPrint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randomm.server.ProtoBufMessage.FingerPrint prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code akka.FingerPrint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.randomm.server.ProtoBufMessage.FingerPrintOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.randomm.server.ProtoBufMessage.internal_static_akka_FingerPrint_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.randomm.server.ProtoBufMessage.internal_static_akka_FingerPrint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.randomm.server.ProtoBufMessage.FingerPrint.class, com.randomm.server.ProtoBufMessage.FingerPrint.Builder.class);
      }

      // Construct using com.randomm.server.ProtoBufMessage.FingerPrint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fingerPrint_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randomm.server.ProtoBufMessage.internal_static_akka_FingerPrint_descriptor;
      }

      public com.randomm.server.ProtoBufMessage.FingerPrint getDefaultInstanceForType() {
        return com.randomm.server.ProtoBufMessage.FingerPrint.getDefaultInstance();
      }

      public com.randomm.server.ProtoBufMessage.FingerPrint build() {
        com.randomm.server.ProtoBufMessage.FingerPrint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.randomm.server.ProtoBufMessage.FingerPrint buildPartial() {
        com.randomm.server.ProtoBufMessage.FingerPrint result = new com.randomm.server.ProtoBufMessage.FingerPrint(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fingerPrint_ = fingerPrint_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randomm.server.ProtoBufMessage.FingerPrint) {
          return mergeFrom((com.randomm.server.ProtoBufMessage.FingerPrint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.randomm.server.ProtoBufMessage.FingerPrint other) {
        if (other == com.randomm.server.ProtoBufMessage.FingerPrint.getDefaultInstance()) return this;
        if (other.hasFingerPrint()) {
          bitField0_ |= 0x00000001;
          fingerPrint_ = other.fingerPrint_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFingerPrint()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.randomm.server.ProtoBufMessage.FingerPrint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.randomm.server.ProtoBufMessage.FingerPrint) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string fingerPrint = 1;
      private java.lang.Object fingerPrint_ = "";
      /**
       * <code>required string fingerPrint = 1;</code>
       */
      public boolean hasFingerPrint() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string fingerPrint = 1;</code>
       */
      public java.lang.String getFingerPrint() {
        java.lang.Object ref = fingerPrint_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fingerPrint_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fingerPrint = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFingerPrintBytes() {
        java.lang.Object ref = fingerPrint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fingerPrint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fingerPrint = 1;</code>
       */
      public Builder setFingerPrint(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fingerPrint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fingerPrint = 1;</code>
       */
      public Builder clearFingerPrint() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fingerPrint_ = getDefaultInstance().getFingerPrint();
        onChanged();
        return this;
      }
      /**
       * <code>required string fingerPrint = 1;</code>
       */
      public Builder setFingerPrintBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fingerPrint_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:akka.FingerPrint)
    }

    static {
      defaultInstance = new FingerPrint(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:akka.FingerPrint)
  }

  public interface CommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string command = 1;
    /**
     * <code>required string command = 1;</code>
     */
    boolean hasCommand();
    /**
     * <code>required string command = 1;</code>
     */
    java.lang.String getCommand();
    /**
     * <code>required string command = 1;</code>
     */
    com.google.protobuf.ByteString
        getCommandBytes();
  }
  /**
   * Protobuf type {@code akka.Command}
   */
  public static final class Command extends
      com.google.protobuf.GeneratedMessage
      implements CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Command(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }

    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              command_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randomm.server.ProtoBufMessage.internal_static_akka_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randomm.server.ProtoBufMessage.internal_static_akka_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.randomm.server.ProtoBufMessage.Command.class, com.randomm.server.ProtoBufMessage.Command.Builder.class);
    }

    public static com.google.protobuf.Parser<Command> PARSER =
        new com.google.protobuf.AbstractParser<Command>() {
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Command(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string command = 1;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private java.lang.Object command_;
    /**
     * <code>required string command = 1;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string command = 1;</code>
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          command_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string command = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      command_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCommandBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCommandBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.randomm.server.ProtoBufMessage.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.randomm.server.ProtoBufMessage.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.randomm.server.ProtoBufMessage.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.randomm.server.ProtoBufMessage.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.randomm.server.ProtoBufMessage.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.randomm.server.ProtoBufMessage.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.randomm.server.ProtoBufMessage.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.randomm.server.ProtoBufMessage.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.randomm.server.ProtoBufMessage.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.randomm.server.ProtoBufMessage.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randomm.server.ProtoBufMessage.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code akka.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.randomm.server.ProtoBufMessage.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.randomm.server.ProtoBufMessage.internal_static_akka_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.randomm.server.ProtoBufMessage.internal_static_akka_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.randomm.server.ProtoBufMessage.Command.class, com.randomm.server.ProtoBufMessage.Command.Builder.class);
      }

      // Construct using com.randomm.server.ProtoBufMessage.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        command_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randomm.server.ProtoBufMessage.internal_static_akka_Command_descriptor;
      }

      public com.randomm.server.ProtoBufMessage.Command getDefaultInstanceForType() {
        return com.randomm.server.ProtoBufMessage.Command.getDefaultInstance();
      }

      public com.randomm.server.ProtoBufMessage.Command build() {
        com.randomm.server.ProtoBufMessage.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.randomm.server.ProtoBufMessage.Command buildPartial() {
        com.randomm.server.ProtoBufMessage.Command result = new com.randomm.server.ProtoBufMessage.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.command_ = command_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randomm.server.ProtoBufMessage.Command) {
          return mergeFrom((com.randomm.server.ProtoBufMessage.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.randomm.server.ProtoBufMessage.Command other) {
        if (other == com.randomm.server.ProtoBufMessage.Command.getDefaultInstance()) return this;
        if (other.hasCommand()) {
          bitField0_ |= 0x00000001;
          command_ = other.command_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommand()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.randomm.server.ProtoBufMessage.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.randomm.server.ProtoBufMessage.Command) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string command = 1;
      private java.lang.Object command_ = "";
      /**
       * <code>required string command = 1;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string command = 1;</code>
       */
      public java.lang.String getCommand() {
        java.lang.Object ref = command_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          command_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string command = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCommandBytes() {
        java.lang.Object ref = command_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          command_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string command = 1;</code>
       */
      public Builder setCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string command = 1;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }
      /**
       * <code>required string command = 1;</code>
       */
      public Builder setCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:akka.Command)
    }

    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:akka.Command)
  }

  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .akka.Message.InputType type = 1 [default = TEXT];
    /**
     * <code>required .akka.Message.InputType type = 1 [default = TEXT];</code>
     */
    boolean hasType();
    /**
     * <code>required .akka.Message.InputType type = 1 [default = TEXT];</code>
     */
    com.randomm.server.ProtoBufMessage.Message.InputType getType();

    // optional int32 chunksCount = 2;
    /**
     * <code>optional int32 chunksCount = 2;</code>
     */
    boolean hasChunksCount();
    /**
     * <code>optional int32 chunksCount = 2;</code>
     */
    int getChunksCount();

    // optional int32 chunkSize = 3;
    /**
     * <code>optional int32 chunkSize = 3;</code>
     */
    boolean hasChunkSize();
    /**
     * <code>optional int32 chunkSize = 3;</code>
     */
    int getChunkSize();

    // optional int32 totalSize = 4;
    /**
     * <code>optional int32 totalSize = 4;</code>
     */
    boolean hasTotalSize();
    /**
     * <code>optional int32 totalSize = 4;</code>
     */
    int getTotalSize();
  }
  /**
   * Protobuf type {@code akka.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.randomm.server.ProtoBufMessage.Message.InputType value = com.randomm.server.ProtoBufMessage.Message.InputType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              chunksCount_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              chunkSize_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              totalSize_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randomm.server.ProtoBufMessage.internal_static_akka_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randomm.server.ProtoBufMessage.internal_static_akka_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.randomm.server.ProtoBufMessage.Message.class, com.randomm.server.ProtoBufMessage.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code akka.Message.InputType}
     */
    public enum InputType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TEXT = 0;</code>
       */
      TEXT(0, 0),
      /**
       * <code>IMAGE = 1;</code>
       */
      IMAGE(1, 1),
      /**
       * <code>AUDIO = 2;</code>
       */
      AUDIO(2, 2),
      /**
       * <code>VIDEO = 3;</code>
       */
      VIDEO(3, 3),
      /**
       * <code>FILE = 4;</code>
       */
      FILE(4, 4),
      ;

      /**
       * <code>TEXT = 0;</code>
       */
      public static final int TEXT_VALUE = 0;
      /**
       * <code>IMAGE = 1;</code>
       */
      public static final int IMAGE_VALUE = 1;
      /**
       * <code>AUDIO = 2;</code>
       */
      public static final int AUDIO_VALUE = 2;
      /**
       * <code>VIDEO = 3;</code>
       */
      public static final int VIDEO_VALUE = 3;
      /**
       * <code>FILE = 4;</code>
       */
      public static final int FILE_VALUE = 4;


      public final int getNumber() { return value; }

      public static InputType valueOf(int value) {
        switch (value) {
          case 0: return TEXT;
          case 1: return IMAGE;
          case 2: return AUDIO;
          case 3: return VIDEO;
          case 4: return FILE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<InputType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<InputType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<InputType>() {
              public InputType findValueByNumber(int number) {
                return InputType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.randomm.server.ProtoBufMessage.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final InputType[] VALUES = values();

      public static InputType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private InputType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:akka.Message.InputType)
    }

    private int bitField0_;
    // required .akka.Message.InputType type = 1 [default = TEXT];
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.randomm.server.ProtoBufMessage.Message.InputType type_;
    /**
     * <code>required .akka.Message.InputType type = 1 [default = TEXT];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .akka.Message.InputType type = 1 [default = TEXT];</code>
     */
    public com.randomm.server.ProtoBufMessage.Message.InputType getType() {
      return type_;
    }

    // optional int32 chunksCount = 2;
    public static final int CHUNKSCOUNT_FIELD_NUMBER = 2;
    private int chunksCount_;
    /**
     * <code>optional int32 chunksCount = 2;</code>
     */
    public boolean hasChunksCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 chunksCount = 2;</code>
     */
    public int getChunksCount() {
      return chunksCount_;
    }

    // optional int32 chunkSize = 3;
    public static final int CHUNKSIZE_FIELD_NUMBER = 3;
    private int chunkSize_;
    /**
     * <code>optional int32 chunkSize = 3;</code>
     */
    public boolean hasChunkSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 chunkSize = 3;</code>
     */
    public int getChunkSize() {
      return chunkSize_;
    }

    // optional int32 totalSize = 4;
    public static final int TOTALSIZE_FIELD_NUMBER = 4;
    private int totalSize_;
    /**
     * <code>optional int32 totalSize = 4;</code>
     */
    public boolean hasTotalSize() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 totalSize = 4;</code>
     */
    public int getTotalSize() {
      return totalSize_;
    }

    private void initFields() {
      type_ = com.randomm.server.ProtoBufMessage.Message.InputType.TEXT;
      chunksCount_ = 0;
      chunkSize_ = 0;
      totalSize_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, chunksCount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, chunkSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, totalSize_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, chunksCount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, chunkSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, totalSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.randomm.server.ProtoBufMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.randomm.server.ProtoBufMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.randomm.server.ProtoBufMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.randomm.server.ProtoBufMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.randomm.server.ProtoBufMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.randomm.server.ProtoBufMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.randomm.server.ProtoBufMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.randomm.server.ProtoBufMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.randomm.server.ProtoBufMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.randomm.server.ProtoBufMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randomm.server.ProtoBufMessage.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code akka.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.randomm.server.ProtoBufMessage.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.randomm.server.ProtoBufMessage.internal_static_akka_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.randomm.server.ProtoBufMessage.internal_static_akka_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.randomm.server.ProtoBufMessage.Message.class, com.randomm.server.ProtoBufMessage.Message.Builder.class);
      }

      // Construct using com.randomm.server.ProtoBufMessage.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.randomm.server.ProtoBufMessage.Message.InputType.TEXT;
        bitField0_ = (bitField0_ & ~0x00000001);
        chunksCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        chunkSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        totalSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randomm.server.ProtoBufMessage.internal_static_akka_Message_descriptor;
      }

      public com.randomm.server.ProtoBufMessage.Message getDefaultInstanceForType() {
        return com.randomm.server.ProtoBufMessage.Message.getDefaultInstance();
      }

      public com.randomm.server.ProtoBufMessage.Message build() {
        com.randomm.server.ProtoBufMessage.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.randomm.server.ProtoBufMessage.Message buildPartial() {
        com.randomm.server.ProtoBufMessage.Message result = new com.randomm.server.ProtoBufMessage.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.chunksCount_ = chunksCount_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.chunkSize_ = chunkSize_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.totalSize_ = totalSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randomm.server.ProtoBufMessage.Message) {
          return mergeFrom((com.randomm.server.ProtoBufMessage.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.randomm.server.ProtoBufMessage.Message other) {
        if (other == com.randomm.server.ProtoBufMessage.Message.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasChunksCount()) {
          setChunksCount(other.getChunksCount());
        }
        if (other.hasChunkSize()) {
          setChunkSize(other.getChunkSize());
        }
        if (other.hasTotalSize()) {
          setTotalSize(other.getTotalSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.randomm.server.ProtoBufMessage.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.randomm.server.ProtoBufMessage.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .akka.Message.InputType type = 1 [default = TEXT];
      private com.randomm.server.ProtoBufMessage.Message.InputType type_ = com.randomm.server.ProtoBufMessage.Message.InputType.TEXT;
      /**
       * <code>required .akka.Message.InputType type = 1 [default = TEXT];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .akka.Message.InputType type = 1 [default = TEXT];</code>
       */
      public com.randomm.server.ProtoBufMessage.Message.InputType getType() {
        return type_;
      }
      /**
       * <code>required .akka.Message.InputType type = 1 [default = TEXT];</code>
       */
      public Builder setType(com.randomm.server.ProtoBufMessage.Message.InputType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .akka.Message.InputType type = 1 [default = TEXT];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.randomm.server.ProtoBufMessage.Message.InputType.TEXT;
        onChanged();
        return this;
      }

      // optional int32 chunksCount = 2;
      private int chunksCount_ ;
      /**
       * <code>optional int32 chunksCount = 2;</code>
       */
      public boolean hasChunksCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 chunksCount = 2;</code>
       */
      public int getChunksCount() {
        return chunksCount_;
      }
      /**
       * <code>optional int32 chunksCount = 2;</code>
       */
      public Builder setChunksCount(int value) {
        bitField0_ |= 0x00000002;
        chunksCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 chunksCount = 2;</code>
       */
      public Builder clearChunksCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chunksCount_ = 0;
        onChanged();
        return this;
      }

      // optional int32 chunkSize = 3;
      private int chunkSize_ ;
      /**
       * <code>optional int32 chunkSize = 3;</code>
       */
      public boolean hasChunkSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 chunkSize = 3;</code>
       */
      public int getChunkSize() {
        return chunkSize_;
      }
      /**
       * <code>optional int32 chunkSize = 3;</code>
       */
      public Builder setChunkSize(int value) {
        bitField0_ |= 0x00000004;
        chunkSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 chunkSize = 3;</code>
       */
      public Builder clearChunkSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chunkSize_ = 0;
        onChanged();
        return this;
      }

      // optional int32 totalSize = 4;
      private int totalSize_ ;
      /**
       * <code>optional int32 totalSize = 4;</code>
       */
      public boolean hasTotalSize() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 totalSize = 4;</code>
       */
      public int getTotalSize() {
        return totalSize_;
      }
      /**
       * <code>optional int32 totalSize = 4;</code>
       */
      public Builder setTotalSize(int value) {
        bitField0_ |= 0x00000008;
        totalSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 totalSize = 4;</code>
       */
      public Builder clearTotalSize() {
        bitField0_ = (bitField0_ & ~0x00000008);
        totalSize_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:akka.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:akka.Message)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_akka_FingerPrint_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_akka_FingerPrint_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_akka_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_akka_Command_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_akka_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_akka_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protoZMQ.proto\022\004akka\"\"\n\013FingerPrint\022\023\n" +
      "\013fingerPrint\030\001 \002(\t\"\032\n\007Command\022\017\n\007command" +
      "\030\001 \002(\t\"\263\001\n\007Message\022+\n\004type\030\001 \002(\0162\027.akka." +
      "Message.InputType:\004TEXT\022\023\n\013chunksCount\030\002" +
      " \001(\005\022\021\n\tchunkSize\030\003 \001(\005\022\021\n\ttotalSize\030\004 \001" +
      "(\005\"@\n\tInputType\022\010\n\004TEXT\020\000\022\t\n\005IMAGE\020\001\022\t\n\005" +
      "AUDIO\020\002\022\t\n\005VIDEO\020\003\022\010\n\004FILE\020\004B\"\n\017com.fata" +
      "ll.akkaB\017ProtoBufMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_akka_FingerPrint_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_akka_FingerPrint_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_akka_FingerPrint_descriptor,
              new java.lang.String[] { "FingerPrint", });
          internal_static_akka_Command_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_akka_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_akka_Command_descriptor,
              new java.lang.String[] { "Command", });
          internal_static_akka_Message_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_akka_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_akka_Message_descriptor,
              new java.lang.String[] { "Type", "ChunksCount", "ChunkSize", "TotalSize", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
